<a href="https://colab.research.google.com/github/Shrez7961/Airbnb-Booking-Analysis/blob/main/Assignment_NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [2]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [3]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [4]:
# Your code here
slice_array = random_integers[:5,3:]
slice_array


array([[140037,  81969],
       [481981, 176739],
       [394863,  25024],
       [485118,  16119],
       [109413, 103399]])

In [5]:
#Average of individual list in slice
for i in range(5):
  avg =slice_array[i].sum()/slice_array[i].size
  print(avg)


111003.0
329360.0
209943.5
250618.5
106406.0


In [6]:
#Average of total slice
avrg=slice_array.sum()/slice_array.size
avrg

201466.2

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [29]:
# Create the 10 points
points=np.random.randint(5,20,size=(10,2))
points

array([[ 5, 19],
       [ 9, 11],
       [ 9, 16],
       [ 9, 12],
       [17, 13],
       [14, 10],
       [11, 10],
       [ 7, 11],
       [ 7, 13],
       [17,  7]])

In [30]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair

def eucledian_distance(point1,point2):
    """Calculates and returns Eucledian Distance"""
    x1,y1=point1
    x2,y2=point2
    return round(((x2-x1)**2+(y2-y1)**2)**0.5,2)                                # calculating eucledian distance 
    
euclidean_distances=[]
for i in range(10):
    inner_llist=[]
    for j in range(10):
        inner_llist.append(eucledian_distance(points[i],points[j]))
    euclidean_distances.append(np.asarray(inner_llist))
euclidean_distances = np.asarray(euclidean_distances)
print(euclidean_distances)

[[ 0.    8.94  5.    8.06 13.42 12.73 10.82  8.25  6.32 16.97]
 [ 8.94  0.    5.    1.    8.25  5.1   2.24  2.    2.83  8.94]
 [ 5.    5.    0.    4.    8.54  7.81  6.32  5.39  3.61 12.04]
 [ 8.06  1.    4.    0.    8.06  5.39  2.83  2.24  2.24  9.43]
 [13.42  8.25  8.54  8.06  0.    4.24  6.71 10.2  10.    6.  ]
 [12.73  5.1   7.81  5.39  4.24  0.    3.    7.07  7.62  4.24]
 [10.82  2.24  6.32  2.83  6.71  3.    0.    4.12  5.    6.71]
 [ 8.25  2.    5.39  2.24 10.2   7.07  4.12  0.    2.   10.77]
 [ 6.32  2.83  3.61  2.24 10.    7.62  5.    2.    0.   11.66]
 [16.97  8.94 12.04  9.43  6.    4.24  6.71 10.77 11.66  0.  ]]


In [31]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.

def manhattan_distance(point1,point2):
    """Calclates and returns Manhattan Distance"""
    x1,y1=point1
    x2,y2=point2
    return round((abs(x2-x1)+abs(y2-y1)),2)                                     # The manhattan distance            

manhattan_distances=[]
for i in range(10):
    inner_llist=[]
    for j in range(10):
        inner_llist.append(manhattan_distance(points[i],points[j]))             
    manhattan_distances.append(np.asarray(inner_llist))
manhattan_distances=np.asarray(manhattan_distances)
print(manhattan_distances)


[[ 0 12  7 11 18 18 15 10  8 24]
 [12  0  5  1 10  6  3  2  4 12]
 [ 7  5  0  4 11 11  8  7  5 17]
 [11  1  4  0  9  7  4  3  3 13]
 [18 10 11  9  0  6  9 12 10  6]
 [18  6 11  7  6  0  3  8 10  6]
 [15  3  8  4  9  3  0  5  7  9]
 [10  2  7  3 12  8  5  0  2 14]
 [ 8  4  5  3 10 10  7  2  0 16]
 [24 12 17 13  6  6  9 14 16  0]]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [32]:
# Your code here


nearest_points_manhattan=[]
for ind,arr in enumerate(manhattan_distances+np.identity(10)*1000):
    nearest_points_manhattan.append((points[ind],points[arr.argmin()]))         # index of the value with min distance is stored and the corrosponding points accesed
    
print(nearest_points_manhattan)

nearest_points_euclidean=[]
for ind,arr in enumerate(euclidean_distances+np.identity(10)*1000):
    nearest_points_euclidean.append((points[ind],points[arr.argmin()]))         # index of the value with min distance is stored and the corrosponding points accesed

print(nearest_points_euclidean)



[(array([ 5, 19]), array([ 9, 16])), (array([ 9, 11]), array([ 9, 12])), (array([ 9, 16]), array([ 9, 12])), (array([ 9, 12]), array([ 9, 11])), (array([17, 13]), array([14, 10])), (array([14, 10]), array([11, 10])), (array([11, 10]), array([ 9, 11])), (array([ 7, 11]), array([ 9, 11])), (array([ 7, 13]), array([ 7, 11])), (array([17,  7]), array([17, 13]))]
[(array([ 5, 19]), array([ 9, 16])), (array([ 9, 11]), array([ 9, 12])), (array([ 9, 16]), array([ 7, 13])), (array([ 9, 12]), array([ 9, 11])), (array([17, 13]), array([14, 10])), (array([14, 10]), array([11, 10])), (array([11, 10]), array([ 9, 11])), (array([ 7, 11]), array([ 9, 11])), (array([ 7, 13]), array([ 7, 11])), (array([17,  7]), array([14, 10]))]


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [12]:
# Your code below ..
np.random.seed(21)
matrix = np.random.randint(1,9,size=(10,10))
matrix


array([[2, 8, 1, 5, 1, 1, 1, 4, 5, 3],
       [8, 2, 3, 1, 7, 8, 5, 6, 6, 2],
       [6, 7, 3, 1, 7, 5, 7, 5, 4, 5],
       [8, 5, 1, 2, 6, 7, 6, 3, 7, 3],
       [1, 5, 3, 1, 6, 6, 1, 3, 4, 1],
       [1, 4, 2, 5, 1, 3, 8, 7, 5, 3],
       [5, 2, 1, 6, 1, 6, 6, 4, 2, 7],
       [4, 5, 5, 7, 7, 5, 7, 2, 1, 3],
       [3, 3, 1, 1, 8, 2, 8, 6, 7, 3],
       [2, 8, 2, 1, 3, 3, 8, 7, 1, 2]])

In [13]:
matrix[:3,:3]

array([[2, 8, 1],
       [8, 2, 3],
       [6, 7, 3]])

In [14]:
len(matrix)

10

In [15]:
for j in range(len(matrix)-2):
    for i in range(len(matrix)-2):
      print(matrix[j:j+3,i:i+3])

[[2 8 1]
 [8 2 3]
 [6 7 3]]
[[8 1 5]
 [2 3 1]
 [7 3 1]]
[[1 5 1]
 [3 1 7]
 [3 1 7]]
[[5 1 1]
 [1 7 8]
 [1 7 5]]
[[1 1 1]
 [7 8 5]
 [7 5 7]]
[[1 1 4]
 [8 5 6]
 [5 7 5]]
[[1 4 5]
 [5 6 6]
 [7 5 4]]
[[4 5 3]
 [6 6 2]
 [5 4 5]]
[[8 2 3]
 [6 7 3]
 [8 5 1]]
[[2 3 1]
 [7 3 1]
 [5 1 2]]
[[3 1 7]
 [3 1 7]
 [1 2 6]]
[[1 7 8]
 [1 7 5]
 [2 6 7]]
[[7 8 5]
 [7 5 7]
 [6 7 6]]
[[8 5 6]
 [5 7 5]
 [7 6 3]]
[[5 6 6]
 [7 5 4]
 [6 3 7]]
[[6 6 2]
 [5 4 5]
 [3 7 3]]
[[6 7 3]
 [8 5 1]
 [1 5 3]]
[[7 3 1]
 [5 1 2]
 [5 3 1]]
[[3 1 7]
 [1 2 6]
 [3 1 6]]
[[1 7 5]
 [2 6 7]
 [1 6 6]]
[[7 5 7]
 [6 7 6]
 [6 6 1]]
[[5 7 5]
 [7 6 3]
 [6 1 3]]
[[7 5 4]
 [6 3 7]
 [1 3 4]]
[[5 4 5]
 [3 7 3]
 [3 4 1]]
[[8 5 1]
 [1 5 3]
 [1 4 2]]
[[5 1 2]
 [5 3 1]
 [4 2 5]]
[[1 2 6]
 [3 1 6]
 [2 5 1]]
[[2 6 7]
 [1 6 6]
 [5 1 3]]
[[6 7 6]
 [6 6 1]
 [1 3 8]]
[[7 6 3]
 [6 1 3]
 [3 8 7]]
[[6 3 7]
 [1 3 4]
 [8 7 5]]
[[3 7 3]
 [3 4 1]
 [7 5 3]]
[[1 5 3]
 [1 4 2]
 [5 2 1]]
[[5 3 1]
 [4 2 5]
 [2 1 6]]
[[3 1 6]
 [2 5 1]
 [1 6 1]]
[[1 6 6]
 [5 1 3]
 [

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [16]:
# Your function below
#Creating a random array
array_random = np.random.randint(10,500,15)
array_random


array([136, 117,  74, 163, 230, 216, 313, 433,  15, 181,  28, 305, 255,
       264, 362])

In [17]:
#Defining a function for calling nearest number from array
def nearest_point(random_array):
  element=int(input("Enter Your Number:\n"))
  
  #Creating a list for numbers less than input number(element)
  lst1=[]
  for i in random_array:
    if i < element:
      lst1.append(i)

  #Get nearest number from inputted number in  lst1
  if len(lst1)>0:
    maxi=max(lst1)

  #Creating a list for numbers greater than input number(element)
  lst2=[]
  for i in random_array:
    if i > element:
      lst2.append(i)

  #Get nearest number from inputted number in  lst2    
  if len(lst2)>0:
    mini=min(lst2)

  #Checking all the conditionals to get the nearest number
  if len(lst1)==0:
    print(f"The nearest point of {element} is {mini}")

  elif len(lst2)==0:
    print(f"The nearest point of {element} is {maxi}")

  elif (element-maxi) == (mini-element):
    print((f"The nearest point of {element} are {maxi} and {mini}"))

  elif (element-maxi) < (mini-element):
    print(f"The nearest point of {element} is {maxi}")
    
  elif(element-maxi) > (mini-element):
    print(f"The nearest point of  {element} is {mini}")

In [18]:
#Sample Inputs
nearest_point(array_random)

Enter Your Number:
300
The nearest point of  300 is 305


Alternate Solution

In [20]:
def get_nearest_value(elem,array):
    """Return the nearest value in the given array for given input"""
    nearest_value = array.flat[np.abs(array - elem).argmin()]                   # flatern and then findind the value with min difrence for given input
    return nearest_value
array=np.random.randint(10,500, size=(1, 15))
print(array)

[[142 172  60 362 323 379 154 237  11 317  11  37 171 256  42]]


In [21]:
ele=int(input("Enter the element for which you want to find the nearest value for "))
print(f"Nearest point to {ele} is {get_nearest_value(ele,array)}")

Enter the element for which you want to find the nearest value for 500
Nearest point to 500 is 379
